# Generated by Django 5.1.4 on 2025-01-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='est_verifie',
            new_name='certification_bio',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='certification',
            new_name='diplome_veterinaire',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_verification',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='licence_professionnelle',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='numero_agrement',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='annees_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='infrastructure_disponible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nombre_animaux',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='specialites',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='surface_exploitee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tarif_horaire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_animaux',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_cultures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='zone_intervention',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='zones_de_consultation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
