# Generated by Django 5.1.4 on 2025-04-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='candidature',
            new_name='candidature_id',
        ),
    ]
