# Generated by Django 5.0.1 on 2025-01-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_est_verifie_utilisateur_certification_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='disponibilite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
