# Generated by Django 5.1.4 on 2025-01-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_utilisateur_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='disponibilite',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Indisponible', 'Indisponible')], default='Disponible', max_length=20),
        ),
    ]
