# Generated by Django 5.1.4 on 2025-01-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categorie_produit_agriculteur_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
