# Generated by Django 5.1.4 on 2025-05-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reponse_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='email',
            field=models.EmailField(default='utilisateur0@gmail.com', max_length=254),
        ),
    ]
