# Generated by Django 5.1.4 on 2025-05-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_candidature_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='core.offreemploi'),
        ),
    ]
