# Generated by Django 5.0.1 on 2025-01-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vente',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
