# Generated by Django 5.1.4 on 2025-01-28 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_utilisateur_is_connected_alter_vente_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_emploi', models.CharField(choices=[('PERMANENT', 'Emploi Permanent'), ('SAISONNIER', 'Emploi Saisonnier'), ('STAGE', 'Stage')], max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('competences_requises', models.TextField()),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('est_active', models.BooleanField(default=True)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agriculteur')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('lettre_motivation', models.TextField()),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouvelle candidature'), ('EN_COURS', 'En cours de traitement'), ('ENTRETIEN', 'Entretien programmé'), ('ACCEPTE', 'Acceptée'), ('REFUSE', 'Refusée')], default='NOUVEAU', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.offreemploi')),
            ],
        ),
    ]
