# Generated by Django 5.1.4 on 2025-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoriediscussion_sujet_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='unitee',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
