# Generated by Django 5.1.4 on 2025-02-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='type_emploi',
            field=models.CharField(max_length=20),
        ),
    ]
