# Generated by Django 5.1.4 on 2025-02-27 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_offreemploi_type_emploi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='employeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
