# Generated by Django 5.1.4 on 2025-03-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_offreemploi_employeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='date_candidature',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='statut',
        ),
        migrations.AddField(
            model_name='candidature',
            name='adresse',
            field=models.TextField(default='Kégué'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='email',
            field=models.EmailField(default='utilisateur0@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='nom',
            field=models.CharField(default='utilisateur0', max_length=100),
        ),
        migrations.AddField(
            model_name='candidature',
            name='numero_telephone',
            field=models.CharField(default='+228 90001212', max_length=20),
        ),
        migrations.AddField(
            model_name='candidature',
            name='prenoms',
            field=models.CharField(default='utilisateur0', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(upload_to='certifications/, null=True, blank=True'),
        ),
    ]
