# Generated by Django 5.1.4 on 2025-03-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_candidature_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('offre', 'candidat')},
        ),
    ]
