# Generated by Django 5.1.4 on 2025-03-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_candidature_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
