# Generated by Django 5.1.4 on 2025-03-29 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_candidature_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepter', models.BooleanField()),
                ('refuser', models.BooleanField()),
                ('motifs', models.CharField(max_length=100)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidature', to='core.candidature')),
            ],
        ),
    ]
